changelog:
  exclude:
    labels:
      - skip-changelog
  categories:
    - title: New
      labels:
        - feature
        - enhancement
    - title: Fixes
      labels:
        - bug
        - security
    - title: Improvements
      labels:
        - "*"
